export const UPDATE_LIST = 'UpdateList'
export const ADD_LIST = 'AddList'
export const DELETE_LIST = 'DeleteList'

export const UPDATE_SONG_MENU_LIST = 'UpdateSongMenuList'
export const ADD_SONG_MENU_LIST = 'AddSongMenuList'

export const UPDATE_SINGER = 'UpdateSinger'
export const ADD_SINGER = 'AddSinger'
export const DELETE_SINGER = 'DeleteSinger'

export const REVISE_PLAYER_LIST_SHOW = 'RevisePlayerListShow'
export const LOAD_PLAYER_LIST = 'LoadPlayerList'
export const ADD_PLAYER_LIST = 'AddPlayerList'
export const REMOVE_PLAYER_LIST = 'RemovePlayerList'
export const REVISE_PLAY = 'RevisePlay'
export const REVISE_CURRENT_TIME = 'ReviseCurrentTime'
export const NOW_INDEX_REVISE_SONG = 'NowIndexReviseSong'
export const REVISE_NOW_INDEX = 'ReviseNowIndex'
export const REVISE_PLAY_MODE = 'RevisePlayMode'
export const REVISE_MAX_PLAYER_SHOW = 'ReviseMaxPlayerShow'
export const SWITCH_SONG = 'SwitchSong'
